### ISSUE TITLE
Bug: "applyMiddleware" updates the schema rather than replacing

### ISSUE THREAD

**Issue by davidgustys** [maticzav/graphql-middleware#63] opened 2018-10-26 15:08 UTC
The cause is where `addResolveFunctionsToSchema` from `graphql-tools` is used which is actually updating the schema rather than replacing it, causing continues re-wrap of middleware on resolver when it is called and this in turn makes queries against the schema slower and slower.

showcase: https://github.com/gdeividas/graphql-middleware
for demonstration run:

```
yarn
npx tsc && npx ava dist/test/showcase.test.js
```

**Comment by gdeividas** [comment] 2018-11-14 16:54
After debugging and trying to find the root cause, the rabbit hole led to grahphql-tools and then I actually found an issue which was also recently opened -  https://github.com/apollographql/graphql-tools/issues/996 . 

So the problem per-se  is not with `graphql-middleware`, but grapqh-middleware should be functional and return *clean* schema.

**Comment by gdeividas** [comment] 2019-02-25 17:37
This probably should not be closed by the bot as its still relevant.

**Comment by mhaagens** [comment] 2019-03-29 10:07
Also having issues with this, breaks HMR in a TypeGraphQL / TypeORM project because it doesn't create a new schema.

**Comment by maticzav** [comment] 2019-05-14 17:59
Shouldn’t be closed.

**Comment by thehappycoder** [comment] 2019-06-28 20:39
ping

**Comment by roschaefer** [comment] 2019-08-13 10:50
This is very relevant: Yesterday I spent the entire day debugging a backend test with `apollo-server-testing`:

I tested a notification middleware and wanted to make sure that only one notification per @-mentioning gets sent. I was extremely confused to see the number of notifications increase **per test  case**, ie. `2*n` for `n` test cases. The reason: For every call of `createServer` which in my case returns an instance of `ApolloServer` and runs `applyMiddleware`, the middlewares are applied on top of the existing ones.

That leads to the following behaviour:
1. Test case:
  * middlewares A->B->C->resolver->C->B->A
2. Test case
  * middlewares A->B->C->A->B->C->resolver->C->B->A->C->B->A
3. Test case
  * middlewares A->B->C->A->B->C->A->B->C->resolver->C->B->A->C->B->A->C->B->A

..and so on.

I can workaround on my side by putting the `createServer` into a `beforeAll`, so the middlewares get applied only once. Nevertheless, if you run into this issue, it's really hard to debug it!

**Comment by BigsonLvrocha** [comment] 2020-08-07 21:02
I've just noticed this issue could be fixed by updating graphql-tools to the newest version, but it drops support for node 10.17.0 or lower.

**Comment by maticzav** [comment] 2020-12-06 07:55
@BigsonLvrocha could you make a PR from your fork and I’ll merge it right away.

**Comment by BigsonLvrocha** [comment] 2020-12-10 14:10
@maticzav there was a pr, but now I've noticed it's gone with the author change, will redo

**Closed** 2020-12-15 18:04 UTC
Labels: bug

**Comment by maticzav** [comment] 2020-12-16 11:38
@BigsonLvrocha I had trouble finding it as well, but after cleaning all the PRs it was the only one left. Seems like I was able to merge it! Thank you 🎉
